# Generated by Django 3.0.5 on 2020-04-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaceList', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeeBUs_APP.PlaceName')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MeeBUs_APP.PlaceName')),
            ],
        ),
    ]
